# Site Settings
title: Curriculum vit√¶
url: 'https://mcfpereira.github.io'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-2

#Profile information
name: M Carolina F. Pereira S.
tagline: Physicist | Data Scientist
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: ''

#sidebar links
email: carolfigueirinhas@gmail.com
skype: carolinafigueirinhas
linkedin: mcfpereira
github: mcfpereira
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
