# Site Settings
title: Curriculum vitæ
url: 'https://mcfpereira.github.io'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-2

#Profile information
name: M Carolina F. Pereira S.
tagline: Physicist | Data Scientist
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

summary: ''O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão. O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500, quando uma misturou os caracteres de um texto para criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas também o salto para a tipografia electrónica, mantendo-se essencialmente inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente com os programas de publicação como o Aldus PageMaker que incluem versões do Lorem Ipsum."


#sidebar links
email: carolfigueirinhas@gmail.com
skype: carolinafigueirinhas
linkedin: mcfpereira
github: mcfpereira
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
